/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import com.sun.glass.events.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class OperasiDuaAngkaGUI extends javax.swing.JFrame {

    /**
     * Creates new form OperasiDuaAngkaGUI
     */
    public OperasiDuaAngkaGUI() {
        initComponents();
    }

    private void filterKeyTyped(java.awt.event.KeyEvent evt){
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||(c==KeyEvent.VK_BACKSPACE)||(c==KeyEvent.VK_DELETE))){
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Masukkan hanya angka");
            evt.consume();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        angkaPertamaTF = new javax.swing.JTextField();
        angkaKeduaTF = new javax.swing.JTextField();
        hasilTF = new javax.swing.JTextField();
        operatorLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tambahBTN = new javax.swing.JButton();
        kurangBTN = new javax.swing.JButton();
        kaliBTN = new javax.swing.JButton();
        bagiBTN = new javax.swing.JButton();
        keluarBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Muhammad Rif'an Salim", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        angkaPertamaTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                angkaPertamaTFKeyTyped(evt);
            }
        });

        angkaKeduaTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                angkaKeduaTFKeyTyped(evt);
            }
        });

        jLabel2.setText("=");

        tambahBTN.setText("Tambah");
        tambahBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahBTNActionPerformed(evt);
            }
        });

        kurangBTN.setText("Kurang");
        kurangBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kurangBTNActionPerformed(evt);
            }
        });

        kaliBTN.setText("Kali");
        kaliBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaliBTNActionPerformed(evt);
            }
        });

        bagiBTN.setText("Bagi");
        bagiBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bagiBTNActionPerformed(evt);
            }
        });

        keluarBTN.setText("Keluar");
        keluarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(angkaPertamaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(operatorLabel)
                        .addGap(12, 12, 12)
                        .addComponent(angkaKeduaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tambahBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kurangBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kaliBTN)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(12, 12, 12)
                        .addComponent(hasilTF, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bagiBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(keluarBTN)))
                .addGap(0, 38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(angkaPertamaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(angkaKeduaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hasilTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(operatorLabel)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambahBTN)
                    .addComponent(kurangBTN)
                    .addComponent(kaliBTN)
                    .addComponent(bagiBTN)
                    .addComponent(keluarBTN))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tambahBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahBTNActionPerformed
        // TODO add your handling code here:
        if(angkaPertamaTF.getText().equals("")||angkaKeduaTF.getText().equals("")){
            JOptionPane.showMessageDialog(null, "input tidak boleh kosong", "warning", JOptionPane.WARNING_MESSAGE);
        }else{
        operatorLabel.setText("+");
        
        double angkaPertama = Double.parseDouble(angkaPertamaTF.getText());
        double angkaKedua = Double.parseDouble(angkaKeduaTF.getText());
        double hasil = angkaPertama + angkaKedua;
        
        hasilTF.setText(Double.toString(hasil));
        }
    }//GEN-LAST:event_tambahBTNActionPerformed

    private void angkaPertamaTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_angkaPertamaTFKeyTyped
        // TODO add your handling code here:
        filterKeyTyped(evt);
    }//GEN-LAST:event_angkaPertamaTFKeyTyped

    private void angkaKeduaTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_angkaKeduaTFKeyTyped
        // TODO add your handling code here:
        filterKeyTyped(evt);
    }//GEN-LAST:event_angkaKeduaTFKeyTyped

    private void kurangBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kurangBTNActionPerformed
        // TODO add your handling code here:
        if(angkaPertamaTF.getText().equals("")||angkaKeduaTF.getText().equals("")){
            JOptionPane.showMessageDialog(null, "input tidak boleh kosong", "warning", JOptionPane.WARNING_MESSAGE);
        }else{
        operatorLabel.setText("-");
        
        double angkaPertama = Double.parseDouble(angkaPertamaTF.getText());
        double angkaKedua = Double.parseDouble(angkaKeduaTF.getText());
        double hasil = angkaPertama - angkaKedua;
        
        hasilTF.setText(Double.toString(hasil));
        }
    }//GEN-LAST:event_kurangBTNActionPerformed

    private void kaliBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaliBTNActionPerformed
        // TODO add your handling code here:
        if(angkaPertamaTF.getText().equals("")||angkaKeduaTF.getText().equals("")){
            JOptionPane.showMessageDialog(null, "input tidak boleh kosong", "warning", JOptionPane.WARNING_MESSAGE);
        }else{
        operatorLabel.setText("x");
        
        double angkaPertama = Double.parseDouble(angkaPertamaTF.getText());
        double angkaKedua = Double.parseDouble(angkaKeduaTF.getText());
        double hasil = angkaPertama * angkaKedua;
        
        hasilTF.setText(Double.toString(hasil));
        }
    }//GEN-LAST:event_kaliBTNActionPerformed

    private void bagiBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bagiBTNActionPerformed
        // TODO add your handling code here:
        if(angkaPertamaTF.getText().equals("")||angkaKeduaTF.getText().equals("")){
            JOptionPane.showMessageDialog(null, "input tidak boleh kosong", "warning", JOptionPane.WARNING_MESSAGE);
        }else{
        operatorLabel.setText("/");
        
        double angkaPertama = Double.parseDouble(angkaPertamaTF.getText());
        double angkaKedua = Double.parseDouble(angkaKeduaTF.getText());
        double hasil = angkaPertama / angkaKedua;
        
        hasilTF.setText(Double.toString(hasil));
        }
    }//GEN-LAST:event_bagiBTNActionPerformed

    private void keluarBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarBTNActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(null, "Apakah yakin akan keluar", "Warning", JOptionPane.YES_NO_OPTION)
                ==JOptionPane.YES_OPTION){
            System.exit(0);
        }
        
    }//GEN-LAST:event_keluarBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OperasiDuaAngkaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OperasiDuaAngkaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OperasiDuaAngkaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OperasiDuaAngkaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OperasiDuaAngkaGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField angkaKeduaTF;
    private javax.swing.JTextField angkaPertamaTF;
    private javax.swing.JButton bagiBTN;
    private javax.swing.JTextField hasilTF;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton kaliBTN;
    private javax.swing.JButton keluarBTN;
    private javax.swing.JButton kurangBTN;
    private javax.swing.JLabel operatorLabel;
    private javax.swing.JButton tambahBTN;
    // End of variables declaration//GEN-END:variables
}
